# Generated by Django 4.2.25 on 2025-11-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="standard_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
